# Generated by Django 5.2.2 on 2026-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_customer_customer_id_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
